[package]
name = "pcm_pyo3"
version = "0.1.0"
edition = "2021"

[lib]
name = "partial_curve_matching"
crate-type = ["cdylib"] # bin, lib, rlib, dylib, cdylib, staticlib, and proc-macro

[dependencies]
ndarray = "0.15.6"
pyo3 = "0.22.2"
pcm = { path = ".." }
