[package]
name = "pcm-rs"
version = "0.1.0"
authors = ["Jeroen van Tubergen <jvtubergen@pm.me>"]
edition = "2021"

[lib]
name = "partial_curve_matching"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15.6"
pyo3 = "0.22.2"
